name: Test Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and run unit tests
        run: ./gradlew test
      - name: Build and run instrumented tests (UI & Accessibility)
        run: ./gradlew connectedAndroidTest
        env:
          # Set up a virtual display for instrumented tests
          DISPLAY: ':99.0'
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/
            app/build/outputs/androidTest-results/

